### ISSUE TITLE
Auth - Working Passwords

### ISSUE THREAD

**Issue by NikkolasJ** [mattjax16/LRC_Tv_Media_Flask#4]
Have a working password system so the user can submit the password and have it loggin or say invalid.

**Comment by mattjax16** [comment]
Stillk debugging appears to be and issue with the falsk_login module 


ERROR CODE

Exception
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.

Traceback (most recent call last)
File "/Users/backoffice/opt/anaconda3/envs/LRC_Tv_Media_Flask/lib/python3.8/site-packages/flask/app.py", line 2088, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/backoffice/opt/anaconda3/envs/LRC_Tv_Media_Flask/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.handle_exception(e)
File "/Users/backoffice/opt/anaconda3/envs/LRC_Tv_Media_Flask/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
response = self.full_dispatch_request()
File "/Users/backoffice/opt/anaconda3/envs/LRC_Tv_Media_Flask/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/backoffice/opt/anaconda3/envs/LRC_Tv_Media_Flask/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/backoffice/opt/anaconda3/envs/LRC_Tv_Media_Flask/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/Users/backoffice/PycharmProjects/LRC_Tv_Media_Flask/LRCmediaUploader/routes.py", line 49, in login
if current_user.is_authenticated:
File "/Users/backoffice/opt/anaconda3/envs/LRC_Tv_Media_Flask/lib/python3.8/site-packages/werkzeug/local.py", line 422, in __get__
obj = instance._get_current_object()
File "/Users/backoffice/opt/anaconda3/envs/LRC_Tv_Media_Flask/lib/python3.8/site-packages/werkzeug/local.py", line 544, in _get_current_object
return self.__local()  # type: ignore
File "/Users/backoffice/opt/anaconda3/envs/LRC_Tv_Media_Flask/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
current_user = LocalProxy(lambda: _get_user())
File "/Users/backoffice/opt/anaconda3/envs/LRC_Tv_Media_Flask/lib/python3.8/site-packages/flask_login/utils.py", line 346, in _get_user
current_app.login_manager._load_user()
File "/Users/backoffice/opt/anaconda3/envs/LRC_Tv_Media_Flask/lib/python3.8/site-packages/flask_login/login_manager.py", line 302, in _load_user
raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by mattjax16** [comment]
ok so I got a base login working but I have to first manually add a user to the data base to it initializes at first which is weird
